### ISSUE TITLE
Test Statistics/Global Class

### ISSUE THREAD

**Issue by eoverberg** [eoverberg/LifeSim#23]
Skeleton classes need to be tested to make sure they are instantiating properly.

## Done: 

- [x] Stats printed to terminal and verified
- [x] Global class attributes printed to terminal and verified

**Comment by RileyRhodes283** [comment]
This is semi completed, until the parser is set up, I won't test further. Note: the arrays work just need to start setting up the "new plant/predator/grazer/obstacle to further test it working.
