### ISSUE TITLE
Extensive testing jsx files

### ISSUE THREAD

**Issue by amjohns1** [eoverberg/LifeSim#60]
- [x] Empty Simulation - zero counts for all entities
- [x] High reproduction rates- configure plants/animals with high reproduction
- [x] Obstacle overload- large number of obstacles
- [x] Survival thresholds- minimum stability (not demo)
- [x] Single entity type - one of each entity
- [x] Pred eat pred
- [x] Grazer eat plant
- [x] Pred reproduce
- [x] Plant Reproduce
- [x] Grazer Reproduce
- [x] Grazer flee pred
- [x] Pred flee based on genes
- [x] Predator ignore?
- [x] Each entity separated by obstacles?
- [x] Speed gene

**Comment by eoverberg** [comment]
- [ ] Pred eat pred
- [ ] Grazer eat plant
- [ ] Pred reproduce
- [ ] Plant Reproduce
- [ ] Grazer Reproduce
- [ ] Grazer flee pred
- [ ] Pred flee based on genes
- [ ] Predator ignore?
- [ ] Each entity separated by obstacles?
